export type TypeUser = {
  avatar: string;
  balance: string;
  created_at: string;
  date_of_birth: string;
  email: string;
  email_verify_code: string;
  gender: "M" | "F";
  id: number;
  premium: "0" | "1";
  name: string;
  nickname: string;
  ref_code: null | string;
  ref_id: null | number;
  ref_user_id: null | number;
  role_id: string;
  surname: string;
  telegram_id: null | number;
  updated_at: string;
  favorite_count: number[];
  tariff_end_date: string | null;
};
